### ISSUE TITLE
Attempt at simultaneous extension of two types (which look the same)

### ISSUE THREAD

**Issue by LucasSeveryn** [innFactory/create-react-app-material-typescript-redux#2]
Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any>'.
  Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any>' are not identical.

**Comment by spoeck** [comment]
Can you give me more information? Was this an error message?

If it was an error, please delete your node_moduls folder and run `npm install` again.

**Comment by LucasSeveryn** [comment]
This was an error message after cloning the git repo and attempting to run it. I just deleted the node_modules folder and ran sudo npm install again.

1. I write 'sudo npm start'
2. I wait as it loads
3. Error appears:
Failed to compile.

/home/lucas/app/live/create-react-app-material-typescript-redux/node_modules/@types/react/index.d.ts
(3735,19): Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any>'.
  Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any>' are not identical.

**Comment by spoeck** [comment]
Hmm.. couldn't reproduce this error :(

Can you try to clone the repo again and do all the steps?

**Comment by LucasSeveryn** [comment]
Just did that, now I'm getting a different error:

```
Starting the development server...

ts-loader: Using typescript@2.7.2 and /home/lucas/app/test/create-react-app-material-typescript-redux/tsconfig.json
Warning: member-ordering - Bad member kind: public-before-private
Failed to compile.

/home/lucas/app/node_modules/@types/react/index.d.ts
(3756,13): Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
```

**Comment by spoeck** [comment]
Ok, this was an versioning issue.
I set fixed version for all dependencies, please delete your node_moduls folder and run `npm i` again.

**Comment by amit131** [comment]
I'm also facing Issue Interface 'Element' cannot simultaneously extend types 'ReactElement' and 'ReactElement'.
Named property 'type' of types 'ReactElement' and 'ReactElement' are not identical. I'm using Windows 8. I tried to clone repo multiple times but same issue. Any idea??

**Comment by amit131** [comment]
Eventually I played around @types/react and @types/react-dom by updating to 16.4.12 & 16.0.7 respectively, then it triggered error  Type 'Middleware' is not generic. I update redux to 4.0.0(latest) and it seems to be working.
