### ISSUE TITLE
Failed to compile with 'npm start'

### ISSUE THREAD

**Issue by baakeydow** [innFactory/create-react-app-material-typescript-redux#6]
Error in `create-react-app-material-typescript-redux/node_modules/@types/react-transition-group/node_modules/@types/react/index.d.ts`

> (2314,14): Duplicate identifier 'LibraryManagedAttributes'.

to make it compile just add [`"skipLibCheck": true`](https://github.com/ant-design/ant-design/issues/11697#issuecomment-422755036) to tsconfig.json

**Comment by klimkjar** [comment]
This happens to me every so often when using yarn - occasionally it pulls in two different versions of @types/react , causing duplicate definitions. Deleting the yarn.lock file and re-running yarn install solved it for me this time.

**Comment by baakeydow** [comment]
Okay I do confirm that at the moment it fails when you do `rm -rf node_modules && yarn install && yarn start`, but indeed it compiles with `npm install && yarn start`
